settings = {
    'model':{
        'mlp': {
            'lr': [0.005],
            'n_folds': 10,
            'epochs': 100,
            'k': 50,
            'dropout_rates': [0.2],
            'neurons_per_layer': [[512, 1024, 2048]],
            'model_names': [
                # 'chemberta_simcse_sum',
                # 'chemberta_simcse_mult',
                # 'chemberta_simcse_mean',
                # 'chemberta_simcse_concat',
                # 'chemberta_deepchem_sum',
                # 'chemberta_deepchem_mult',
                # 'chemberta_deepchem_mean',
                # 'chemberta_deepchem_concat',
                # 'gpt_sum',
                # 'gpt_mult',
                # 'gpt_mean',
                # 'gpt_concat',
                # 'bert_sum',
                # 'bert_mult',
                # 'bert_mean',
                # 'bert_concat',
                # 'mol2vec_sum',
                # 'mol2vec_mult',
                # 'mol2vec_mean',
                # 'mol2vec_concat',
                # 'doc2vec_sum',
                # 'doc2vec_mult',
                # 'doc2vec_mean',
                # 'doc2vec_concat',
                # 'doc2vec_mult',
                # 'doc2vec_concat',
                # 'doc2vec_mean',
                # 'sbert_sum',
                # 'sbert_mult',
                # 'sbert_mean',
                # 'sbert_concat',
                # 'bert_smiles',
                # 'zeros'
            ]
        },
        'gnn': {
            'lr': 0.01,
            'epochs': 10,
            'iter': 1,
            'hidden_channels': 64,
            'model_names': [
                # 'zeros',
                # 'chemberta_simcse_sum',
                'chemberta_deepchem_sum',
                # 'gpt_sum_small',
                # 'gpt_sum_large',
                # 'gpt_mult',
                # 'gpt_mean',
                # 'gpt_concat',
                # 'bert_sum',
                # 'mol2vec_sum',
                # 'doc2vec_sum',
                # 'doc2vec_mult',
                # 'doc2vec_concat',
                # 'doc2vec_mean',
                # 'sbert_sum',
                # 'bert_smiles',
            ]
        }
    }
}